<?php
$pokemons = [
1=>["nome"=>"Dragonite","numero"=>149,"tipos"=>["Dragon","Flying"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png","descricao"=>"Dragonite é um Pokémon dos tipos Dragão e Voador. É conhecido por sua grande força e por conseguir voar muito rápido.","altura"=>"2,2 m","peso"=>"210 kg","evolucoes"=>["Dratini","Dragonair","Dragonite"]],
2=>["nome"=>"Tyranitar","numero"=>248,"tipos"=>["Rock","Dark"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/248.png","descricao"=>"Tyranitar é um Pokémon dos tipos Pedra e Sombrio. Seu corpo é muito resistente.","altura"=>"2,0 m","peso"=>"202 kg","evolucoes"=>["Larvitar","Pupitar","Tyranitar"]],
3=>["nome"=>"Salamence","numero"=>373,"tipos"=>["Dragon","Flying"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/373.png","descricao"=>"Salamence é um Pokémon dos tipos Dragão e Voador. Ele possui asas e grande poder de ataque.","altura"=>"1,5 m","peso"=>"102,6 kg","evolucoes"=>["Bagon","Shelgon","Salamence"]],
4=>["nome"=>"Metagross","numero"=>376,"tipos"=>["Steel","Psychic"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/376.png","descricao"=>"Metagross é um Pokémon dos tipos Aço e Psíquico. Ele possui um cérebro muito poderoso.","altura"=>"1,6 m","peso"=>"550 kg","evolucoes"=>["Beldum","Metang","Metagross"]],
5=>["nome"=>"Garchomp","numero"=>445,"tipos"=>["Dragon","Ground"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png","descricao"=>"Garchomp é um Pokémon dos tipos Dragão e Terrestre. É conhecido por sua velocidade e força.","altura"=>"1,9 m","peso"=>"95 kg","evolucoes"=>["Gible","Gabite","Garchomp"]],
6=>["nome"=>"Hydreigon","numero"=>635,"tipos"=>["Dark","Dragon"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/635.png","descricao"=>"Hydreigon é um Pokémon dos tipos Sombrio e Dragão. Possui três cabeças e é bastante agressivo.","altura"=>"1,8 m","peso"=>"160 kg","evolucoes"=>["Deino","Zweilous","Hydreigon"]],
7=>["nome"=>"Goodra","numero"=>706,"tipos"=>["Dragon"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/706.png","descricao"=>"Goodra é um Pokémon do tipo Dragão. Apesar de ser muito forte, é conhecido por ser amigável.","altura"=>"2,0 m","peso"=>"150,5 kg","evolucoes"=>["Goomy","Sliggoo","Goodra"]],
8=>["nome"=>"Kommo-o","numero"=>784,"tipos"=>["Dragon","Fighting"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/784.png","descricao"=>"Kommo-o é um Pokémon dos tipos Dragão e Lutador. Suas escamas funcionam como uma armadura.","altura"=>"1,6 m","peso"=>"78,2 kg","evolucoes"=>["Jangmo-o","Hakamo-o","Kommo-o"]],
9=>["nome"=>"Dragapult","numero"=>887,"tipos"=>["Dragon","Ghost"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/887.png","descricao"=>"Dragapult é um Pokémon dos tipos Dragão e Fantasma. É muito rápido e costuma carregar Dreepy.","altura"=>"3,0 m","peso"=>"50 kg","evolucoes"=>["Dreepy","Drakloak","Dragapult"]],
10=>["nome"=>"Hisuian Goodra","numero"=>"706-H","tipos"=>["Steel","Dragon"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10162.png","descricao"=>"A forma de Hisui de Goodra possui uma carapaça metálica muito resistente.","altura"=>"1,7 m","peso"=>"334,1 kg","evolucoes"=>["Goomy","Sliggoo de Hisui","Goodra de Hisui"]],
11=>["nome"=>"Baxcalibur","numero"=>998,"tipos"=>["Dragon","Ice"],"imagem"=>"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/998.png","descricao"=>"Baxcalibur é um Pokémon dos tipos Dragão e Gelo. Ele possui uma lâmina em suas costas.","altura"=>"2,1 m","peso"=>"210 kg","evolucoes"=>["Frigibax","Arctibax","Baxcalibur"]]
];
function classeTipo($tipo){ return strtolower($tipo); }
?>